# Generated by Django 4.1 on 2022-08-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalnotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('bind_size', models.CharField(blank=True, max_length=200, null=True)),
                ('book_is_hardcover', models.BooleanField(default=True)),
                ('colorbook', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Cuaderno',
                'verbose_name_plural': 'Cuadernos',
            },
        ),
        migrations.AlterModelOptions(
            name='bindings',
            options={'verbose_name': 'Binding', 'verbose_name_plural': 'Bindings'},
        ),
        migrations.AddField(
            model_name='bindings',
            name='colorbook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
